# èœå•
menu:
  name: èœå•
  event: message
  priority: 2000
  rule:
  - reg: ^æŒ‡ä»¤$ #æŒ‡ä»¤
    ml: æŒ‡ä»¤ #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: getmenu #æ‰§è¡Œå‡½æ•°
    des: è·å–æœºå™¨äººæŒ‡ä»¤ #åŠŸèƒ½ä»‹ç»

# é˜»æ­¢å…¶ä»–æ’ä»¶çš„æŒ‡ä»¤è¿è¡Œ
bindMl:
  name: é˜»æ­¢æŒ‡ä»¤è¿è¡Œ
  event: message
  priority: 2000
  hide: 1
  rule:
  - reg: ^#éªŒè½¦.*$ #æŒ‡ä»¤
    ml: "#éªŒè½¦" #æŒ‡ä»¤å±•ç¤º
    isOnline: 0 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: bindYc #æ‰§è¡Œå‡½æ•°
    des: é˜»æ­¢éªŒè½¦åŠŸèƒ½ #åŠŸèƒ½ä»‹ç»

  - reg: ^æˆ’(ğŸ¦Œ|é¹¿)$ #æŒ‡ä»¤
    ml: æˆ’ğŸ¦Œã€æˆ’é¹¿ #æŒ‡ä»¤å±•ç¤º
    isOnline: 0 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: bindJl #æ‰§è¡Œå‡½æ•°
    des: é˜»æ­¢æˆ’æ’¸åŠŸèƒ½ #åŠŸèƒ½ä»‹ç»
    errs:
      img: ./plugins/suibian-plugin/res/img/é¹¿.jpg
      msg: å½“å‰ä¸ºä¸–ç•ŒğŸ¦Œç®¡æ—¥ï¼Œç¦æ­¢æˆ’ğŸ¦Œï¼Just Do it!ğŸ¦Œç®¡å§ï¼Œéª„å‚²çš„å°‘å¹´ï¼
      type: èœå°±å¤šç»ƒ

  - reg: ^(çš„é£æ ¼å·¥ä¼šç»è´¹æœºæ„è¡Œå®¶ ğŸ¦Œ|å•Šæ²™å‘æ²™å‘å£«å¤§å¤« é¹¿)$ #æŒ‡ä»¤
    ml: ğŸ¦Œã€é¹¿ #æŒ‡ä»¤å±•ç¤º
    isOnline: 0 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: bindL #æ‰§è¡Œå‡½æ•°
    des: é˜»æ­¢æˆ’æ’¸åŠŸèƒ½ #åŠŸèƒ½ä»‹ç»
    errs:
      img: ./plugins/suibian-plugin/res/img/æ‰‹æ”¾ä¸‹.png
      msg: å½“å‰ä¸ºä¸–ç•Œæˆ’ğŸ¦Œæ—¥ï¼Œæˆ‘ç»™ä½ æœ€åçš„ç–¼çˆ±æ˜¯æ‰‹æ”¾å¼€~ä¸æƒ³ç”¨è¨€è¯­æ‹‰æ‰¯æ‰€ä»¥é€‰æ‹©ä¸è´£æ€ª~
      type: ä¼‘å…»ç”Ÿæ¯

# å†™çœŸæŒ‡ä»¤
xiezhen:
  name: å†™çœŸæŒ‡ä»¤
  event: message
  priority: 2000
  rule:
  - reg: ^#å†™çœŸ$ #æŒ‡ä»¤
    ml: "#å†™çœŸ" #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: getMl #æ‰§è¡Œå‡½æ•°
    des: å±•ç¤ºå†™çœŸåˆ—è¡¨ #åŠŸèƒ½ä»‹ç»

  - reg: ^#çœ‹.*$ #æŒ‡ä»¤
    ml: "#çœ‹+åºå·" #æŒ‡ä»¤å±•ç¤º
    isOnline: 0 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: getRandomXz #æ‰§è¡Œå‡½æ•°
    des: è·å–æŒ‡å®šåºå·è‰ºæœ¯å®¶çš„éšæœºå†™çœŸ #åŠŸèƒ½ä»‹ç»

# ç›²ç›’
manghe:
  name: ç›²ç›’
  event: message
  priority: 2000
  rule:
  - reg: ^(ğŸ‘€|ç›¯)$ #æŒ‡ä»¤
    ml: ğŸ‘€ã€ç›¯ #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: cpmh #æ‰§è¡Œå‡½æ•°
    des: éšæœºæŠ½å–è½¦ç‰Œç›²ç›’ #åŠŸèƒ½ä»‹ç»

  - reg: ^(ğŸ¥µ)$ #æŒ‡ä»¤
    ml: ğŸ¥µ #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: fashao #æ‰§è¡Œå‡½æ•°
    des: ä¸çŸ¥é“ä¼šå‘å‡ºæ¥ä»€ä¹ˆä¸œè¥¿ #åŠŸèƒ½ä»‹ç»

# embyç³»åˆ—çš„æŒ‡ä»¤
emby:
  name: emby
  event: message
  priority: 2000
  rule:
  - reg: ^#æ³¨å†Œ$ #æŒ‡ä»¤
    ml: '#æ³¨å†Œ' #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: embyReg #æ‰§è¡Œå‡½æ•°
    des: embyè‡ªåŠ©æ³¨å†Œ #åŠŸèƒ½ä»‹ç»

  - reg: ^#æ¸…ç†$ #æŒ‡ä»¤
    ml: "#æ¸…ç†" #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: embyDeleteUserWithoutPassword #æ‰§è¡Œå‡½æ•°
    des: åˆ é™¤æ³¨å†Œ24å°æ—¶æœªè®¾ç½®å¯†ç çš„è´¦å· #åŠŸèƒ½ä»‹ç»

  - reg: ^ğŸ˜$ #æŒ‡ä»¤
    ml: ğŸ˜ #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: sjtj #æ‰§è¡Œå‡½æ•°
    des: éšæœºæ¨èembyé‡Œçš„ç”µå½± #åŠŸèƒ½ä»‹ç»

  - reg: ^#åº“å­˜$ #æŒ‡ä»¤
    ml: "#åº“å­˜" #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: getEmbyInfo #æ‰§è¡Œå‡½æ•°
    des: è·å–embyåª’ä½“åº“èµ„æºæ•°é‡ #åŠŸèƒ½ä»‹ç»

# å¼ å˜´æœ‰æ€¥äº‹
zhangzui:
  name: å¼ å˜´
  event: message
  priority: 2000
  rule:
  - reg: ^å¼ å˜´.*$ #æŒ‡ä»¤
    ml: "å¼ å˜´ã€å¼ å˜´***" #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: zz #æ‰§è¡Œå‡½æ•°
    des: å¼ å˜´æœ‰æ€¥äº‹ #åŠŸèƒ½ä»‹ç»

# GIF
gif:
  name: åŠ¨å›¾
  event: message
  priority: 2000
  rule:
  - reg: ^(æ›´æ–°gif|æ›´æ–°GIF)$ #æŒ‡ä»¤
    ml: æ›´æ–°gifã€æ›´æ–°GIF #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: updateGif #æ‰§è¡Œå‡½æ•°
    des: æ›´æ–°æœºå™¨äººçš„gifåº“ #åŠŸèƒ½ä»‹ç»

  - reg: ^(gif|GIF|æŠ–ä¸€ä¸‹)$ #æŒ‡ä»¤
    ml: gifã€GIFã€æŠ–ä¸€ä¸‹ #æŒ‡ä»¤å±•ç¤º
    isOnline: 1 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
    fnc: getGif #æ‰§è¡Œå‡½æ•°
    des: éšæœºè·å–gif #åŠŸèƒ½ä»‹ç»

# éŸ³ä¹
# music:
#   name: éŸ³ä¹
#   event: message
#   priority: 2000
#   rule:
#   - reg: ^å¬æ­Œ$ #æŒ‡ä»¤
#     ml: å¬æ­Œ #æŒ‡ä»¤å±•ç¤º
#     isOnline: 0 #æ˜¯å¦ä¸Šçº¿å¯ç”¨
#     fnc: getMusic #æ‰§è¡Œå‡½æ•°
#     des: è·å–éŸ³ä¹åˆ—è¡¨ #åŠŸèƒ½ä»‹ç»
